apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-cephfs-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cdk-cephfs
  name: cdk-cephfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cdk-cephfs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cdk-cephfs
    spec:
      volumes:
        - name: pv-cephfs
          persistentVolumeClaim:
            claimName: pv-cephfs-claim
      containers:
      - image: calvinhartwell/cdk-cats:latest
        imagePullPolicy: ""
        name: cdk-cephfs
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources: {}
        volumeMounts:
          - mountPath: "/cephfs-mount"
            name: pv-cephfs
      restartPolicy: Always
      serviceAccountName: ""
status: {}
