# Please refer to the OpenStack Charms Deployment Guide for more information.
# https://docs.openstack.org/project-deploy-guide/charm-deployment-guide
#
# NOTE: Please review the value for the configuration option
#       `bridge-interface-mappings` for the `ovn-chassis` charm (see `data-port` variable).
#       Refer to the [Open Virtual Network (OVN)](https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-ovn.html)
#       section of the [OpenStack Charms Deployment Guide](https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/)
#       for more information.

series: focal
variables:
  #openstack-origin: &openstack-origin cloud:focal-xena
  openstack-origin: &openstack-origin distro
  data-port: &data-port br-ex:public
  worker-multiplier: &worker-multiplier 0.25
  osd-devices: &osd-devices "/dev/sdb /dev/sda"
  expected-osd-count: &expected-osd-count 5
  expected-mon-count: &expected-mon-count 3
  # Octavia management certs
  # These should be specified relative to the bundle with include-base64
  # ex: include-base64://../certs/controller_ca.pem
  # juju config octavia     lb-mgmt-issuing-cacert="$(base64 ../server_ca/certs/ca.cert.pem)"     lb-mgmt-issuing-ca-private-key="$(base64 ../server_ca/private/ca.key.pem)"     lb-mgmt-issuing-ca-key-passphrase=foobar     lb-mgmt-controller-cacert="$(base64 ../client_ca/certs/ca.cert.pem)"     lb-mgmt-controller-cert="$(base64 ../client_ca/private/client.cert-and-key.pem)"
  #
  lb-mgmt-issuing-cacert:             &lb-mgmt-issuing-cacert              include-base64://../tls/temp/certs/server_ca/certs/ca.cert.pem
  lb-mgmt-issuing-ca-private-key:     &lb-mgmt-issuing-ca-private-key      include-base64://../tls/temp/certs/server_ca/private/ca.key.pem
  lb-mgmt-issuing-ca-key-passphrase:  &lb-mgmt-issuing-ca-key-passphrase   foobar
  lb-mgmt-controller-cacert:          &lb-mgmt-controller-cacert           include-base64://../tls/temp/certs/client_ca/certs/ca.cert.pem
  lb-mgmt-controller-cert:            &lb-mgmt-controller-cert             include-base64://../tls/temp/certs/client_ca/private/client.cert-and-key.pem
  designate-nameservers: &designate-nameservers "ns1.openstack.maas."

machines:
  '0':
    constraints: tags=node02
  '1':
    constraints: tags=node03
  '2':
    constraints: tags=node07
  '3':
    constraints: tags=node09
  '4':
    constraints: tags=node10
  '5':
    constraints: tags=node05
  '6':
    constraints: tags=node06
  '7':
    constraints: tags=node01
    #  '8':
    #    constraints: tags=node04
relations:
- [ openstack-dashboard, octavia-dashboard ]
- ["designate:dns-backend", "designate-bind:dns-backend"]
- ["designate:identity-service", "keystone:identity-service"]
- ["designate:amqp", "rabbitmq-server:amqp"]
- ["designate:coordinator-memcached", "memcached:cache"]
- ["designate:dnsaas", "neutron-api:external-dns"]
- [ "designate:shared-db", "designate-mysql-router:shared-db"]
- [ "mysql-innodb-cluster:db-router", "designate-mysql-router:db-router"]
- ["vault:certificates", "designate:certificates"]
- ["vault:certificates", "designate-bind:certificates"]
- [ "octavia:amqp", "rabbitmq-server:amqp" ]
- [ octavia-mysql-router:shared-db, octavia:shared-db ]
- [ "octavia:identity-service", "keystone:identity-service" ]
- [ "octavia:neutron-api", "neutron-api:neutron-load-balancer" ]
# - [ octavia-diskimage-retrofit, glance-simplestreams-sync ]
- [ "glance-simplestreams-sync:identity-service", "keystone:identity-service" ]
# - [ octavia-diskimage-retrofit, keystone ]
- ["octavia-mysql-router:db-router", "mysql-innodb-cluster:db-router"]
- - vault:certificates
  - glance-simplestreams-sync:certificates
- - ovn-chassis-octavia:ovsdb-subordinate
  - octavia:ovsdb-subordinate
- - ovn-chassis-octavia:certificates
  - vault:certificates
- - ovn-chassis-octavia:ovsdb
  - ovn-central:ovsdb
- - ovn-central:ovsdb-cms
  - octavia:ovsdb-cms
- - vault:certificates
  - octavia:certificates
- - barbican-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - barbican-mysql-router:shared-db
  - barbican:shared-db
- - barbican-vault:certificates
  - vault:certificates
- - barbican-vault:secrets-storage
  - vault:secrets
- - barbican-vault:secrets
  - barbican:secrets
- - barbican:amqp
  - rabbitmq-server:amqp
- - barbican:certificates
  - vault:certificates
- - barbican:identity-service
  - keystone:identity-service
- - nova-compute:amqp
  - rabbitmq-server:amqp
- - heat:identity-service
  - keystone:identity-service
- - magnum:identity-service
  - keystone:identity-service
- - nova-cloud-controller:identity-service
  - keystone:identity-service
- - glance:identity-service
  - keystone:identity-service
- - neutron-api:identity-service
  - keystone:identity-service
- - heat:amqp
  - rabbitmq-server:amqp
- - magnum:amqp
  - rabbitmq-server:amqp
- - neutron-api:amqp
  - rabbitmq-server:amqp
- - glance:amqp
  - rabbitmq-server:amqp
- - nova-cloud-controller:image-service
  - glance:image-service
- - nova-compute:image-service
  - glance:image-service
- - nova-cloud-controller:cloud-compute
  - nova-compute:cloud-compute
- - nova-cloud-controller:amqp
  - rabbitmq-server:amqp
- - openstack-dashboard:identity-service
  - keystone:identity-service
- - nova-cloud-controller:neutron-api
  - neutron-api:neutron-api
- - cinder:image-service
  - glance:image-service
- - cinder:amqp
  - rabbitmq-server:amqp
- - cinder:identity-service
  - keystone:identity-service
- - cinder:cinder-volume-service
  - nova-cloud-controller:cinder-volume-service
- - cinder-ceph:storage-backend
  - cinder:storage-backend
- - ceph-mon:client
  - nova-compute:ceph
- - nova-compute:ceph-access
  - cinder-ceph:ceph-access
- - ceph-mon:client
  - cinder-ceph:ceph
- - ceph-mon:client
  - glance:ceph
- - ceph-osd:mon
  - ceph-mon:osd
- - ntp:juju-info
  - nova-compute:juju-info
- - ceph-radosgw:mon
  - ceph-mon:radosgw
- - ceph-radosgw:identity-service
  - keystone:identity-service
- - placement:identity-service
  - keystone:identity-service
- - placement:placement
  - nova-cloud-controller:placement
- - keystone:shared-db
  - keystone-mysql-router:shared-db
- - heat:shared-db
  - heat-mysql-router:shared-db
- - magnum:shared-db
  - magnum-mysql-router:shared-db
- - cinder:shared-db
  - cinder-mysql-router:shared-db
- - glance:shared-db
  - glance-mysql-router:shared-db
- - nova-cloud-controller:shared-db
  - nova-mysql-router:shared-db
- - neutron-api:shared-db
  - neutron-mysql-router:shared-db
- - openstack-dashboard:shared-db
  - dashboard-mysql-router:shared-db
- - placement:shared-db
  - placement-mysql-router:shared-db
- - vault:shared-db
  - vault-mysql-router:shared-db
- - heat-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - magnum-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - keystone-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - cinder-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - nova-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - glance-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - neutron-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - dashboard-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - placement-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - vault-mysql-router:db-router
  - mysql-innodb-cluster:db-router
- - neutron-api-plugin-ovn:neutron-plugin
  - neutron-api:neutron-plugin-api-subordinate
- - openstack-dashboard
  - magnum-dashboard
- - ovn-central:certificates
  - vault:certificates
- - ovn-central:ovsdb-cms
  - neutron-api-plugin-ovn:ovsdb-cms
- - neutron-api:certificates
  - vault:certificates
- - ovn-chassis:nova-compute
  - nova-compute:neutron-plugin
- - ovn-chassis:certificates
  - vault:certificates
- - ovn-chassis:ovsdb
  - ovn-central:ovsdb
- - vault:certificates
  - neutron-api-plugin-ovn:certificates
- - vault:certificates
  - magnum:certificates
- - vault:certificates
  - heat:certificates
- - vault:certificates
  - cinder:certificates
- - vault:certificates
  - glance:certificates
- - vault:certificates
  - keystone:certificates
- - vault:certificates
  - nova-cloud-controller:certificates
- - vault:certificates
  - openstack-dashboard:certificates
- - vault:certificates
  - placement:certificates
- - vault:certificates
  - ceph-radosgw:certificates
- - vault:certificates
  - mysql-innodb-cluster:certificates
applications:
  ceph-mon:
    annotations:
      gui-x: '790'
      gui-y: '1540'
    charm: cs:ceph-mon-61
    num_units: 3
    bindings:
      "": oam-space
    options:
      expected-osd-count: *expected-osd-count
      monitor-count: *expected-mon-count
      source: *openstack-origin
    to:
    - lxd:0
    - lxd:1
    - lxd:2
  ceph-osd:
    charm: cs:ceph-osd-315
    num_units: 6
    bindings:
      "": oam-space
    options:
      osd-devices: *osd-devices
      source: *openstack-origin
    to:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    # - '6'
    # - '7'
  ceph-radosgw:
    annotations:
      gui-x: '850'
      gui-y: '900'
    charm: cs:ceph-radosgw-300
    num_units: 1
    bindings:
      "": oam-space
    options:
      source: *openstack-origin
      namespace-tenants: True
    to:
    - lxd:3
  cinder-mysql-router:
    annotations:
      gui-x: '900'
      gui-y: '1400'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  cinder:
    annotations:
      gui-x: '980'
      gui-y: '1270'
    charm: cs:cinder-317
    bindings:
      "": oam-space
    num_units: 1
    options:
      block-device: None
      glance-api-version: 2
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:4
  cinder-ceph:
    annotations:
      gui-x: '1120'
      gui-y: '1400'
    charm: cs:cinder-ceph-268
    bindings:
      "": oam-space
    num_units: 0
  glance-mysql-router:
    annotations:
      gui-x: '-290'
      gui-y: '1400'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  glance:
    annotations:
      gui-x: '-230'
      gui-y: '1270'
    charm: cs:glance-312
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:0
  heat:
    charm: ch:heat
    channel: stable
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:0
  heat-mysql-router:
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  barbican:
    charm: ch:barbican
    channel: stable
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:1
  barbican-mysql-router:
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  barbican-vault:
    bindings:
      "": oam-space
    charm: ch:barbican-vault
    channel: stable
  magnum:
    charm: ch:magnum
    channel: ussuri/edge
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:2
  magnum-mysql-router:
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  magnum-dashboard:
    charm: ch:magnum-dashboard
    channel: ussuri/edge
    bindings:
      "": oam-space
  keystone-mysql-router:
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  keystone:
    charm: cs:keystone-658
    num_units: 1
    bindings:
      "": oam-space
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
      preferred-api-version: 3.0
      admin-password: admin #for lab
    to:
    - lxd:3
  neutron-mysql-router:
    annotations:
      gui-x: '505'
      gui-y: '1385'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  neutron-api-plugin-ovn:
    annotations:
      gui-x: '690'
      gui-y: '1385'
    charm: cs:neutron-api-plugin-ovn-10
    bindings:
      "": oam-space
  neutron-api:
    annotations:
      gui-x: '580'
      gui-y: '1270'
    charm: cs:neutron-api-302
    bindings:
      "": oam-space
    num_units: 1
    options:
      neutron-security-groups: true
      flat-network-providers: physnet1
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
      enable-ml2-port-security: True
    to:
    - lxd:4
  placement-mysql-router:
    annotations:
      gui-x: '1320'
      gui-y: '1385'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  placement:
    annotations:
      gui-x: '1320'
      gui-y: '1270'
    charm: cs:placement-31
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:1
  nova-mysql-router:
    annotations:
      gui-x: '-30'
      gui-y: '1385'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  nova-cloud-controller:
    annotations:
      gui-x: '35'
      gui-y: '1270'
    charm: cs:nova-cloud-controller-361
    bindings:
      "": oam-space
    num_units: 1
    options:
      network-manager: Neutron
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
    to:
    - lxd:0
  nova-compute:
    annotations:
      gui-x: '190'
      gui-y: '890'
    charm: cs:nova-compute-337
    bindings:
      "": oam-space
    num_units: 8
    options:
      config-flags: default_ephemeral_format=ext4
      enable-live-migration: true
      enable-resize: true
      migration-auth-type: ssh
      openstack-origin: *openstack-origin
    to:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
  ntp:
    annotations:
      gui-x: '315'
      gui-y: '1030'
    charm: cs:ntp-47
    bindings:
      "": oam-space
    num_units: 0
  dashboard-mysql-router:
    annotations:
      gui-x: '510'
      gui-y: '1030'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  openstack-dashboard:
    annotations:
      gui-x: '585'
      gui-y: '900'
    charm: cs:openstack-dashboard-318
    bindings:
      "": oam-space
    num_units: 1
    options:
      openstack-origin: *openstack-origin
    to:
    - lxd:1
  rabbitmq-server:
    annotations:
      gui-x: '300'
      gui-y: '1550'
    charm: cs:rabbitmq-server-117
    bindings:
      "": oam-space
    num_units: 1
    to:
    - lxd:2
  mysql-innodb-cluster:
    annotations:
      gui-x: '535'
      gui-y: '1550'
    charm: cs:mysql-innodb-cluster-15
    bindings:
      "": oam-space
    num_units: 3
    to:
    - lxd:3
    - lxd:4
    - lxd:2
  ovn-central:
    annotations:
      gui-x: '70'
      gui-y: '1550'
    charm: cs:ovn-central-15
    bindings:
      "": oam-space
    num_units: 3
    options:
      source: *openstack-origin
    to:
    - lxd:0
    - lxd:1
    - lxd:2
  ovn-chassis:
    annotations:
      gui-x: '120'
      gui-y: '1030'
    charm: cs:ovn-chassis-21
    bindings:
      "": oam-space
    # Please update the `bridge-interface-mappings` to values suitable for the
    # hardware used in your deployment. See the referenced documentation at the
    # top of this file.
    options:
      ovn-bridge-mappings: physnet1:br-ex
      bridge-interface-mappings: *data-port
  ovn-chassis-octavia:
    charm: cs:ovn-chassis
  octavia-mysql-router:
    charm: cs:mysql-router
  octavia:
    charm: cs:octavia
    bindings:
      "": oam-space
    num_units: 1
    options:
      worker-multiplier: *worker-multiplier
      openstack-origin: *openstack-origin
      use-internal-endpoints: True
      loadbalancer-topology: 'ACTIVE_STANDBY'
      lb-mgmt-issuing-cacert: *lb-mgmt-issuing-cacert
      lb-mgmt-issuing-ca-private-key: *lb-mgmt-issuing-ca-private-key
      lb-mgmt-issuing-ca-key-passphrase: *lb-mgmt-issuing-ca-key-passphrase
      lb-mgmt-controller-cacert: *lb-mgmt-controller-cacert
      lb-mgmt-controller-cert: *lb-mgmt-controller-cert
    to:
    - lxd:3
  octavia-dashboard:
    charm: cs:octavia-dashboard
  # octavia-diskimage-retrofit:
  #   charm: cs:octavia-diskimage-retrofit
  #   revision: 108
  #   options:
  #     retrofit-uca-pocket: ussuri
  #     amp-image-tag: octavia-amphora
  #     retrofit-series: focal
  glance-simplestreams-sync:
    charm: cs:glance-simplestreams-sync
    bindings:
      "": oam-space
    num_units: 1
    options:
      source: ppa:simplestreams-dev/trunk
      run: false
      use_swift: false
      mirror_list: "[{url: 'http://cloud-images.ubuntu.com/releases/', name_prefix: 'ubuntu:released', path: 'streams/v1/index.sjson', max: 1, item_filters: ['release~(bionic|focal|jammy)', 'arch~(x86_64|amd64)', 'ftype~(disk1.img|disk.img)']}]"
    to:
    - lxd:4
  vault-mysql-router:
    annotations:
      gui-x: '1535'
      gui-y: '1560'
    charm: cs:mysql-router-6
    bindings:
      "": oam-space
  vault:
    annotations:
      gui-x: '1610'
      gui-y: '1430'
    charm: cs:vault-54
    bindings:
      "": oam-space
    num_units: 1
    to:
    - lxd:0
    options:
      auto-generate-root-ca-cert: true
  designate:
    charm: cs:designate
    bindings:
      "": oam-space
    num_units: 1
    options:
      openstack-origin: *openstack-origin
      use-internal-endpoints: True
      nameservers: *designate-nameservers
    to:
    - lxd:1
  designate-bind:
    charm: cs:designate-bind
    bindings:
      "": oam-space
    num_units: 1
    options:
      use-internal-endpoints: True
      allowed_nets: ""
      forwarders: ""
      recursion: True
      disable-dnssec-validation: True
    to:
    - lxd:2
  designate-mysql-router:
    charm: cs:mysql-router
    bindings:
      "": oam-space
  memcached:
    charm: cs:memcached
    bindings:
      "": oam-space
    num_units: 1
    options:
      allow-ufw-ip6-softfail: True
    to:
    - designate-bind/0
